version: "3"

services:
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
        environment:
            - SPRING_PROFILES_ACTIVE=devtest
            - DB_HOST=10.200.10.1:3306
            - DB_NAME=myapp_db

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
